apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janus-core.fullname" . }}
  labels:
    {{- include "janus-core.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
