apiVersion: v1
kind: Service
metadata:
  name: {{ include "janus-core.fullname" . }}
  labels:
    {{- include "janus-core.labels" . | nindent 4 }}
  {{- if .Values.prometheus.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.prometheus.port }}"
    prometheus.io/path: "{{ .Values.prometheus.path }}"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "janus-core.selectorLabels" . | nindent 4 }}
